package yzx.com.queue.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import yzx.com.queue.entity.OrderInfo;
import yzx.com.queue.entity.OrderType;

import yzx.com.queue.greendao.OrderInfoDao;
import yzx.com.queue.greendao.OrderTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderInfoDaoConfig;
    private final DaoConfig orderTypeDaoConfig;

    private final OrderInfoDao orderInfoDao;
    private final OrderTypeDao orderTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderInfoDaoConfig = daoConfigMap.get(OrderInfoDao.class).clone();
        orderInfoDaoConfig.initIdentityScope(type);

        orderTypeDaoConfig = daoConfigMap.get(OrderTypeDao.class).clone();
        orderTypeDaoConfig.initIdentityScope(type);

        orderInfoDao = new OrderInfoDao(orderInfoDaoConfig, this);
        orderTypeDao = new OrderTypeDao(orderTypeDaoConfig, this);

        registerDao(OrderInfo.class, orderInfoDao);
        registerDao(OrderType.class, orderTypeDao);
    }
    
    public void clear() {
        orderInfoDaoConfig.clearIdentityScope();
        orderTypeDaoConfig.clearIdentityScope();
    }

    public OrderInfoDao getOrderInfoDao() {
        return orderInfoDao;
    }

    public OrderTypeDao getOrderTypeDao() {
        return orderTypeDao;
    }

}
