package yzx.com.queue.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import yzx.com.queue.entity.OrderType;

import yzx.com.queue.greendao.OrderTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderTypeDaoConfig;

    private final OrderTypeDao orderTypeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderTypeDaoConfig = daoConfigMap.get(OrderTypeDao.class).clone();
        orderTypeDaoConfig.initIdentityScope(type);

        orderTypeDao = new OrderTypeDao(orderTypeDaoConfig, this);

        registerDao(OrderType.class, orderTypeDao);
    }
    
    public void clear() {
        orderTypeDaoConfig.clearIdentityScope();
    }

    public OrderTypeDao getOrderTypeDao() {
        return orderTypeDao;
    }

}
